name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 3'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        java: [8, 11]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v5
    - run: sbt -v "++ 2.13.4" "testOnly com.github.tototoshi.slick.MySQLJodaSupportSpec"
